setwd("~/Course4_ExploratoryDataAnalysis/Week1/project")
library(data.table)
p_total = fread("household_power_consumption.txt", na.strings = "?")
p_total$Date <- as.Date(p_total$Date, format = "%d/%m/%Y")
p <- subset(p_total, subset = (Date >= "2007-02-01" & Date <= "2007-02-02"))
rm(p_total)
p$DateTime <- paste(as.Date(p$Date), p$Time)
p$DateTime <- as.POSIXct(p$DateTime)
p$Global_active_power <- as.numeric(p$Global_active_power)
p$Sub_metering_1 <- as.numeric(p$Sub_metering_1)
p$Sub_metering_2 <- as.numeric(p$Sub_metering_2)
p$Sub_metering_3 <- as.numeric(p$Sub_metering_3)
p$Voltage <- as.numeric(p$Voltage)